// 青科竞赛雷达 · 195 项认定竞赛数据（由 app/competitions-data.ts 生成）
// 报名/比赛时间为演示用示例数据，正式系统由采集方案提供。
window.COMPETITIONS = [
  {
    "id": 1,
    "name": "全国大学生市场调查与分析大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-01-05",
    "regEnd": "2026-02-04",
    "eventStart": "2026-02-19",
    "eventEnd": "2026-02-21",
    "official": "https://www.china-cssc.com",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 2,
    "name": "全国大学生电子商务“创新、创意及创业”挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-01-12",
    "regEnd": "2026-02-14",
    "eventStart": "2026-03-06",
    "eventEnd": "2026-03-09",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 3,
    "name": "全国大学生物流设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-01-19",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-21",
    "eventEnd": "2026-03-25",
    "official": "https://www.clpp.org.cn",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 4,
    "name": "全国高校商业精英挑战赛·会计与商业管理案例竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-12",
    "regEnd": "2026-10-08",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-17",
    "official": "https://www.ccpitedu.org",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 5,
    "name": "“学创杯”全国大学生创业综合模拟大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-15",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-12-03",
    "official": "http://www.xcbds.com",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 6,
    "name": "全国大学生金融科技创新能力大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-18",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-14",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 7,
    "name": "全国大学生国际贸易技能大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 8,
    "name": "全国大学生能源经济学术创意大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 9,
    "name": "全国高校企业价值创造实战竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 10,
    "name": "全国大学生智慧供应链创新创业挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 11,
    "name": "全国高校商业精英挑战赛·品牌策划竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-02-04",
    "regEnd": "2026-03-11",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-17",
    "official": "https://www.ccpitedu.org",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 12,
    "name": "“东方财富杯”全国大学生金融挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-02-11",
    "regEnd": "2026-03-21",
    "eventStart": "2026-04-30",
    "eventEnd": "2026-05-03",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 13,
    "name": "全国大学生管理决策模拟大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-01-09",
    "regEnd": "2026-02-19",
    "eventStart": "2026-03-06",
    "eventEnd": "2026-03-10",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 14,
    "name": "全国大学生财税技能大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-17",
    "regEnd": "2026-10-23",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-17",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 15,
    "name": "山东省大学生商务谈判大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "经管学院",
    "regStart": "2026-09-20",
    "regEnd": "2026-11-02",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-28",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 16,
    "name": "全国大学生统计建模大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-23",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-19",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 17,
    "name": "山东省大学生科技节·创新创业大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "经管学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 18,
    "name": "山东省大学生电子商务技能竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "经管学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 19,
    "name": "全国大学生数据分析大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 20,
    "name": "全国高校大数据管理与应用大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 21,
    "name": "全国大学生人力资源职业技能大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-01-25",
    "regEnd": "2026-03-06",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-02",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 22,
    "name": "全国大学生经济学综合博弈实验大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-02-01",
    "regEnd": "2026-03-16",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-18",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 23,
    "name": "全国大学生资产评估知识竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-02-08",
    "regEnd": "2026-03-26",
    "eventStart": "2026-04-30",
    "eventEnd": "2026-05-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 24,
    "name": "全国大学生房地产策划大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-22",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-22",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 25,
    "name": "山东省大学生金融素养大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-25",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-02",
    "eventEnd": "2026-12-08",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 26,
    "name": "山东省大学生商业模式创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-09-03",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-24",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 27,
    "name": "全国大学生“三创赛”直播电商赛道",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "经管学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "http://www.3chuang.net",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 28,
    "name": "全国大学生程序设计竞赛（ICPC 区域赛）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 29,
    "name": "中国大学生计算机设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "https://jsjds.blcu.edu.cn",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 30,
    "name": "“蓝桥杯”全国软件和信息技术专业人才大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "https://dasai.lanqiao.cn",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 31,
    "name": "中国高校计算机大赛·程序设计天梯赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-15",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-18",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 32,
    "name": "全国大学生信息安全竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-22",
    "regEnd": "2026-03-11",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-03",
    "official": "https://www.ciscn.cn",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 33,
    "name": "全国大学生软件测试大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-29",
    "regEnd": "2026-03-21",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-19",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 34,
    "name": "中国软件杯大学生软件设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-09-27",
    "regEnd": "2026-11-02",
    "eventStart": "2026-12-17",
    "eventEnd": "2026-12-22",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 35,
    "name": "中国大学生服务外包创新创业大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-09-05",
    "regEnd": "2026-10-18",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-13",
    "official": "http://www.fwwb.org.cn",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 36,
    "name": "全国大学生物联网设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-09-08",
    "regEnd": "2026-10-08",
    "eventStart": "2026-10-28",
    "eventEnd": "2026-10-30",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 37,
    "name": "中国高校计算机大赛·网络技术挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 38,
    "name": "全国大学生大数据技能竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 39,
    "name": "全国大学生人工智能创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 40,
    "name": "中国机器人及人工智能大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 41,
    "name": "全国大学生嵌入式芯片与系统设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-05",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-02",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 42,
    "name": "全国大学生网络安全精英赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-12",
    "regEnd": "2026-03-06",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-18",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 43,
    "name": "全国大学生数据挖掘挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-19",
    "regEnd": "2026-02-19",
    "eventStart": "2026-03-06",
    "eventEnd": "2026-03-10",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 44,
    "name": "全国大学生区块链技术创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-09-07",
    "regEnd": "2026-10-03",
    "eventStart": "2026-10-28",
    "eventEnd": "2026-11-02",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 45,
    "name": "山东省大学生计算机能力挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "信息学院",
    "regStart": "2026-09-10",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-18",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 46,
    "name": "山东省大学生程序设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "信息学院",
    "regStart": "2026-09-13",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-11-29",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 47,
    "name": "全国大学生软件创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 48,
    "name": "中国大学生开源软件创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 49,
    "name": "中国大学生计算机博弈大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 50,
    "name": "山东省大学生网络安全技能竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "信息学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 51,
    "name": "山东省大学生大数据应用创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-02-04",
    "regEnd": "2026-03-06",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-02",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 52,
    "name": "全国大学生智能媒体创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-02-11",
    "regEnd": "2026-03-16",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-18",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 53,
    "name": "全国大学生虚拟现实创新设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "信息学院",
    "regStart": "2026-01-09",
    "regEnd": "2026-02-14",
    "eventStart": "2026-03-21",
    "eventEnd": "2026-03-25",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 54,
    "name": "山东省大学生软件设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "信息学院",
    "regStart": "2026-09-12",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-12-02",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 55,
    "name": "全国大学生机械创新设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-09-15",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-18",
    "official": "http://www.umic.edu.cn",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 56,
    "name": "全国大学生工程训练综合能力竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-09-18",
    "regEnd": "2026-10-18",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-09",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 57,
    "name": "全国大学生先进成图技术与产品信息建模创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 58,
    "name": "全国大学生电子设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "https://www.nuedc-training.com.cn",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 59,
    "name": "中国智能制造挑战赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 60,
    "name": "全国大学生机器人大赛 RoboMaster",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "https://www.robomaster.com",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 61,
    "name": "全国大学生智能汽车竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-01-25",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-18",
    "official": "https://smartcar.cdstm.cn",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 62,
    "name": "全国大学生节能减排社会实践与科技竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-02-01",
    "regEnd": "2026-03-11",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-03",
    "official": "http://www.jienengjianpai.org",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 63,
    "name": "中国大学生机械工程创新创意大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-02-08",
    "regEnd": "2026-03-21",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-19",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 64,
    "name": "中国高校智能机器人创意大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-09-17",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-02",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 65,
    "name": "全国大学生三维数字化创新设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-09-20",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-23",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 66,
    "name": "山东省大学生机电产品创新设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "机电学院",
    "regStart": "2026-09-23",
    "regEnd": "2026-11-02",
    "eventStart": "2026-12-02",
    "eventEnd": "2026-12-04",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 67,
    "name": "全国大学生工业工程与精益管理创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 68,
    "name": "全国大学生焊接创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 69,
    "name": "全国大学生金相技能大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 70,
    "name": "山东省大学生智能制造大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 71,
    "name": "全国大学生创新体验竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "机电学院",
    "regStart": "2026-01-15",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-02",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 72,
    "name": "山东省大学生机器人大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "机电学院",
    "regStart": "2026-01-22",
    "regEnd": "2026-03-06",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-18",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 73,
    "name": "中国大学生田径锦标赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-01-29",
    "regEnd": "2026-03-16",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-04",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 74,
    "name": "中国大学生篮球联赛（CUBA）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-09-22",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-02",
    "eventEnd": "2026-12-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 75,
    "name": "中国大学生足球联赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-09-25",
    "regEnd": "2026-11-07",
    "eventStart": "2026-12-17",
    "eventEnd": "2026-12-23",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 76,
    "name": "中国大学生排球联赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-09-03",
    "regEnd": "2026-10-03",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-19",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 77,
    "name": "全国大学生武术套路锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 78,
    "name": "全国大学生跆拳道锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 79,
    "name": "全国大学生健美操锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 80,
    "name": "全国大学生乒乓球锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 81,
    "name": "全国大学生羽毛球锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-01-05",
    "regEnd": "2026-02-19",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-18",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 82,
    "name": "全国大学生网球锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-01-12",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-03",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 83,
    "name": "中国大学生游泳锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-01-19",
    "regEnd": "2026-03-11",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-19",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 84,
    "name": "全国大学生定向越野锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-09-27",
    "regEnd": "2026-10-23",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-17",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 85,
    "name": "山东省大学生运动会",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "体育学院",
    "regStart": "2026-09-05",
    "regEnd": "2026-10-08",
    "eventStart": "2026-10-28",
    "eventEnd": "2026-11-03",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 86,
    "name": "山东省大学生田径锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "体育学院",
    "regStart": "2026-09-08",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-14",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 87,
    "name": "山东省大学生篮球联赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 88,
    "name": "山东省大学生健美操啦啦操比赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 89,
    "name": "全国大学生跳绳锦标赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "体育学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 90,
    "name": "全国大学生广告艺术大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "https://www.sun-ada.net",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 91,
    "name": "中国大学生广告艺术节学院奖",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-02-04",
    "regEnd": "2026-03-26",
    "eventStart": "2026-04-10",
    "eventEnd": "2026-04-12",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 92,
    "name": "全国高校数字艺术设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-02-11",
    "regEnd": "2026-04-05",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-28",
    "official": "https://www.ncda.org.cn",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 93,
    "name": "中国好创意暨全国数字艺术设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-01-09",
    "regEnd": "2026-02-09",
    "eventStart": "2026-03-06",
    "eventEnd": "2026-03-10",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 94,
    "name": "全国大学生工业设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-09-07",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-17",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 95,
    "name": "米兰设计周·中国高校设计学科师生优秀作品展",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-09-10",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-12-03",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 96,
    "name": "山东省大学生艺术展演活动",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "艺术学院",
    "regStart": "2026-09-13",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-24",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 97,
    "name": "全国大学生摄影大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 98,
    "name": "全国高校艺术设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 99,
    "name": "全国大学生动漫设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 100,
    "name": "全国大学生书法大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 101,
    "name": "全国大学生服装设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-01-25",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-02",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 102,
    "name": "中国国际大学生纪录片大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-02-01",
    "regEnd": "2026-03-06",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-18",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 103,
    "name": "山东省大学生创意设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-02-08",
    "regEnd": "2026-03-16",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-04",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 104,
    "name": "山东省大学生微电影大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "艺术学院",
    "regStart": "2026-09-12",
    "regEnd": "2026-10-08",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-27",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 105,
    "name": "山东省大学生美术作品展",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "艺术学院",
    "regStart": "2026-09-15",
    "regEnd": "2026-10-18",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-13",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 106,
    "name": "全国大学生数学建模竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-09-18",
    "regEnd": "2026-10-28",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-19",
    "official": "https://www.mcm.edu.cn",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 107,
    "name": "全国大学生数学竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "http://www.cmathc.cn",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 108,
    "name": "全国大学生物理竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 109,
    "name": "全国大学生物理实验竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 110,
    "name": "全国大学生光电设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 111,
    "name": "美国大学生数学建模竞赛（MCM/ICM）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-01-15",
    "regEnd": "2026-02-19",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-18",
    "official": "https://www.comap.com",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 112,
    "name": "全国大学生力学竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-01-22",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-03",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 113,
    "name": "中国大学生物理学术竞赛（CUPT）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-01-29",
    "regEnd": "2026-03-11",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-19",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 114,
    "name": "山东省大学生数学竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "数理学院",
    "regStart": "2026-09-17",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-22",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 115,
    "name": "山东省大学生物理竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-09-20",
    "regEnd": "2026-11-02",
    "eventStart": "2026-12-02",
    "eventEnd": "2026-12-08",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 116,
    "name": "全国大学生数学应用能力竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "数理学院",
    "regStart": "2026-09-23",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-11-29",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 117,
    "name": "“外研社·国才杯”全国英语演讲大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "https://uchallenge.unipus.cn",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 118,
    "name": "“外研社·国才杯”全国英语写作大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "https://uchallenge.unipus.cn",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 119,
    "name": "“外研社·国才杯”全国英语阅读大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "https://uchallenge.unipus.cn",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 120,
    "name": "全国大学生英语竞赛（NECCS）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "http://www.chinaneccs.cn",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 121,
    "name": "山东省高校学生跨文化能力大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "外语学院",
    "regStart": "2026-01-05",
    "regEnd": "2026-02-14",
    "eventStart": "2026-03-01",
    "eventEnd": "2026-03-03",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 122,
    "name": "全国英语口译大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-01-12",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-19",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 123,
    "name": "“外研社·国才杯”全国英语辩论赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-01-19",
    "regEnd": "2026-03-06",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-04",
    "official": "https://uchallenge.unipus.cn",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 124,
    "name": "全国大学生日语演讲比赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-09-22",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-12-02",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 125,
    "name": "全国大学生德语演讲比赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-09-25",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-18",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 126,
    "name": "“外教社·词达人杯”全国大学生英语词汇能力大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "外语学院",
    "regStart": "2026-09-03",
    "regEnd": "2026-10-13",
    "eventStart": "2026-12-02",
    "eventEnd": "2026-12-04",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 127,
    "name": "山东省大学生英语演讲比赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "外语学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 128,
    "name": "全国大学生智慧农业创新创业大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 129,
    "name": "全国大学生乡村振兴创意大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 130,
    "name": "山东省大学生“互联网+”创新创业大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "S",
    "levelName": "省级",
    "unit": "高密校区",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 131,
    "name": "全国大学生低碳科技竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-02-04",
    "regEnd": "2026-03-21",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-27",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 132,
    "name": "全国大学生科普作品创作大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-02-11",
    "regEnd": "2026-03-31",
    "eventStart": "2026-05-10",
    "eventEnd": "2026-05-13",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 133,
    "name": "山东省大学生科技节·科普创作大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "高密校区",
    "regStart": "2026-01-09",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-20",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 134,
    "name": "全国大学生生态环保创意大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-09-27",
    "regEnd": "2026-11-02",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-27",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 135,
    "name": "山东省大学生创新创业训练计划项目成果展示",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-09-05",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-18",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 136,
    "name": "全国大学生青年志愿服务项目大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高密校区",
    "regStart": "2026-09-08",
    "regEnd": "2026-10-08",
    "eventStart": "2026-11-07",
    "eventEnd": "2026-11-09",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 137,
    "name": "山东省大学生传统文化创意大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "高密校区",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 138,
    "name": "全国大学生化工设计竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "化工学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 139,
    "name": "全国大学生化工实验大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "化工学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 140,
    "name": "全国大学生过程装备实践与创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "化工学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 141,
    "name": "山东省大学生化工过程实验技能竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "化工学院",
    "regStart": "2026-01-25",
    "regEnd": "2026-03-16",
    "eventStart": "2026-04-10",
    "eventEnd": "2026-04-12",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 142,
    "name": "全国大学生高分子材料创新创业大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高分子科学与工程学院",
    "regStart": "2026-02-01",
    "regEnd": "2026-03-26",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 143,
    "name": "全国大学生橡胶制品设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高分子科学与工程学院",
    "regStart": "2026-02-08",
    "regEnd": "2026-03-11",
    "eventStart": "2026-04-15",
    "eventEnd": "2026-04-19",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 144,
    "name": "全国大学生“双碳”材料创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "高分子科学与工程学院",
    "regStart": "2026-09-07",
    "regEnd": "2026-10-03",
    "eventStart": "2026-11-07",
    "eventEnd": "2026-11-12",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 145,
    "name": "山东省大学生高分子材料创新设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "高分子科学与工程学院",
    "regStart": "2026-09-10",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-28",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 146,
    "name": "全国大学生环境生态科技创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "环境与安全工程学院",
    "regStart": "2026-09-13",
    "regEnd": "2026-10-23",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-09",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 147,
    "name": "全国大学生安全科学与工程实践创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "环境与安全工程学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 148,
    "name": "全国大学生绿色科技创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "环境与安全工程学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 149,
    "name": "山东省大学生环保创意大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "环境与安全工程学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 150,
    "name": "全国大学生材料设计创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "材料科学与工程学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 151,
    "name": "全国大学生失效分析大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "材料科学与工程学院",
    "regStart": "2026-01-15",
    "regEnd": "2026-02-14",
    "eventStart": "2026-03-01",
    "eventEnd": "2026-03-03",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 152,
    "name": "全国大学生热处理创新创业大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "材料科学与工程学院",
    "regStart": "2026-01-22",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-19",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 153,
    "name": "山东省大学生材料创新设计竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "材料科学与工程学院",
    "regStart": "2026-01-29",
    "regEnd": "2026-03-06",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-04",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 154,
    "name": "全国大学生自动化系统应用大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "自动化与电子工程学院",
    "regStart": "2026-09-12",
    "regEnd": "2026-10-18",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-12",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 155,
    "name": "中国大学生自动化技术创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "自动化与电子工程学院",
    "regStart": "2026-09-15",
    "regEnd": "2026-10-28",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-23",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 156,
    "name": "山东省大学生电子设计竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "自动化与电子工程学院",
    "regStart": "2026-09-18",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-14",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 157,
    "name": "全国大学生化学实验邀请赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "化学与分子工程学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 158,
    "name": "全国大学生化学实验创新设计大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "化学与分子工程学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 159,
    "name": "山东省大学生化学实验技能竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "化学与分子工程学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 160,
    "name": "全国大学生海洋知识竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "海洋科学与生物工程学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 161,
    "name": "全国大学生生物科技创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "海洋科学与生物工程学院",
    "regStart": "2026-01-05",
    "regEnd": "2026-02-09",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-18",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 162,
    "name": "山东省大学生海洋生物创新大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "海洋科学与生物工程学院",
    "regStart": "2026-01-12",
    "regEnd": "2026-02-19",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-03",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 163,
    "name": "全国大学生生命科学竞赛（创新创业类）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "生物工程学院",
    "regStart": "2026-01-19",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-20",
    "official": "https://www.educol.cn",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 164,
    "name": "全国大学生生命科学竞赛（科学探究类）",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "生物工程学院",
    "regStart": "2026-09-17",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-12",
    "eventEnd": "2026-11-17",
    "official": "https://www.educol.cn",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 165,
    "name": "山东省大学生生物工程创新设计大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "生物工程学院",
    "regStart": "2026-09-20",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-27",
    "eventEnd": "2026-12-03",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 166,
    "name": "中德工业智造创新大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "中德科技学院",
    "regStart": "2026-09-23",
    "regEnd": "2026-11-02",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-14",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 167,
    "name": "山东省大学生德语风采大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "中德科技学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-09-28",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 168,
    "name": "全国大学生国际交流英语竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "中德科技学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-15",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 169,
    "name": "全国大学生新闻传播能力大赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "传媒学院",
    "regStart": "2026-06-20",
    "regEnd": "2026-10-04",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-27",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 170,
    "name": "山东省大学生短视频创作大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "传媒学院",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-07",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 171,
    "name": "全国大学生广告艺术大赛（短视频赛道）",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "传媒学院",
    "regStart": "2026-02-04",
    "regEnd": "2026-03-16",
    "eventStart": "2026-04-10",
    "eventEnd": "2026-04-12",
    "official": "https://www.sun-ada.net",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 172,
    "name": "全国大学生模拟法庭竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "法学院",
    "regStart": "2026-02-11",
    "regEnd": "2026-03-26",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 173,
    "name": "全国学生“学宪法 讲宪法”活动",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "法学院",
    "regStart": "2026-01-09",
    "regEnd": "2026-02-24",
    "eventStart": "2026-03-31",
    "eventEnd": "2026-04-04",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 174,
    "name": "山东省大学生法律知识竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "法学院",
    "regStart": "2026-09-22",
    "regEnd": "2026-10-28",
    "eventStart": "2026-12-12",
    "eventEnd": "2026-12-17",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 175,
    "name": "全国大学生讲思政课公开课展示活动",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "马克思主义学院",
    "regStart": "2026-09-25",
    "regEnd": "2026-11-07",
    "eventStart": "2026-12-27",
    "eventEnd": "2027-01-02",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 176,
    "name": "山东省大学生马克思主义理论素养竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "马克思主义学院",
    "regStart": "2026-09-03",
    "regEnd": "2026-10-03",
    "eventStart": "2026-10-23",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 177,
    "name": "全国高校大学生微电影展示活动（思政主题）",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "马克思主义学院",
    "regStart": "2026-06-30",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-12",
    "eventEnd": "2026-10-15",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 178,
    "name": "中国国际大学生创新大赛",
    "category": "A",
    "categoryName": "A 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "创新创业学院",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-01",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-26",
    "official": "https://cy.ncss.cn",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 179,
    "name": "全国大学生创新创业训练计划年会展示",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "创新创业学院",
    "regStart": "2026-07-10",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-06",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 180,
    "name": "山东省大学生创业计划竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "创新创业学院",
    "regStart": "2026-07-15",
    "regEnd": "2026-10-07",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-17",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 181,
    "name": "“挑战杯”全国大学生课外学术科技作品竞赛",
    "category": "A",
    "categoryName": "A 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "校团委",
    "regStart": "2026-01-25",
    "regEnd": "2026-03-11",
    "eventStart": "2026-03-26",
    "eventEnd": "2026-03-28",
    "official": "https://www.tiaozhanbei.net",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 182,
    "name": "“挑战杯”中国大学生创业计划竞赛",
    "category": "A",
    "categoryName": "A 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "校团委",
    "regStart": "2026-02-01",
    "regEnd": "2026-03-21",
    "eventStart": "2026-04-10",
    "eventEnd": "2026-04-13",
    "official": "https://www.tiaozhanbei.net",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 183,
    "name": "全国大学生暑期社会实践优秀成果展示",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "校团委",
    "regStart": "2026-02-08",
    "regEnd": "2026-03-31",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-29",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 184,
    "name": "全国大学生通识素养竞赛",
    "category": "B",
    "categoryName": "B 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "教务处",
    "regStart": "2026-09-27",
    "regEnd": "2026-10-23",
    "eventStart": "2026-11-17",
    "eventEnd": "2026-11-22",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 185,
    "name": "山东省大学生学业规划大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "教务处",
    "regStart": "2026-09-05",
    "regEnd": "2026-10-08",
    "eventStart": "2026-11-07",
    "eventEnd": "2026-11-13",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 186,
    "name": "全国大学生知识竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "教务处",
    "regStart": "2026-09-08",
    "regEnd": "2026-10-18",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-24",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 187,
    "name": "全国大学生心理健康教育微课大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "学生工作处",
    "regStart": "2026-06-20",
    "regEnd": "2026-09-28",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-25",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 188,
    "name": "山东省大学生心理健康节系列活动",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "学生工作处",
    "regStart": "2026-06-25",
    "regEnd": "2026-10-01",
    "eventStart": "2026-11-01",
    "eventEnd": "2026-11-05",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 189,
    "name": "全国大学生资助政策知识竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "学生工作处",
    "regStart": "2026-06-30",
    "regEnd": "2026-10-04",
    "eventStart": "2026-11-11",
    "eventEnd": "2026-11-16",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  },
  {
    "id": 190,
    "name": "全国大学生国际视野英语竞赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "国际交流与合作处",
    "regStart": "2026-07-05",
    "regEnd": "2026-10-07",
    "eventStart": "2026-10-22",
    "eventEnd": "2026-10-28",
    "official": "",
    "note": "报名以官方公告为准，参赛信息以组委会最终通知为准。"
  },
  {
    "id": 191,
    "name": "山东省大学生国际文化交流大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "国际交流与合作处",
    "regStart": "2026-01-15",
    "regEnd": "2026-03-06",
    "eventStart": "2026-04-10",
    "eventEnd": "2026-04-12",
    "official": "",
    "note": "本年度首次纳入校内重点支持名单，鼓励新生参加。"
  },
  {
    "id": 192,
    "name": "全国大学生国际组织胜任力大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "国际交流与合作处",
    "regStart": "2026-01-22",
    "regEnd": "2026-03-16",
    "eventStart": "2026-04-25",
    "eventEnd": "2026-04-28",
    "official": "",
    "note": "赛事通知、赛题与评分标准详见官网最新公告。"
  },
  {
    "id": 193,
    "name": "全国大学生信息素养大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "图书馆",
    "regStart": "2026-01-29",
    "regEnd": "2026-03-01",
    "eventStart": "2026-03-16",
    "eventEnd": "2026-03-20",
    "official": "",
    "note": "校级选拔后统一推荐报名，具体以校内通知为准。"
  },
  {
    "id": 194,
    "name": "山东省大学生阅读推广风采大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "S",
    "levelName": "省级",
    "unit": "图书馆",
    "regStart": "2026-09-07",
    "regEnd": "2026-10-13",
    "eventStart": "2026-11-22",
    "eventEnd": "2026-11-27",
    "official": "",
    "note": "面向全校本科生、研究生开放，优先支持跨学院组队。"
  },
  {
    "id": 195,
    "name": "全国大学生中华经典诵读大赛",
    "category": "C",
    "categoryName": "C 类",
    "level": "G",
    "levelName": "国家级",
    "unit": "图书馆",
    "regStart": "2026-09-10",
    "regEnd": "2026-10-23",
    "eventStart": "2026-12-07",
    "eventEnd": "2026-12-13",
    "official": "",
    "note": "需经校内初赛选拔，入选团队由牵头学院组织集训。"
  }
];
